{{- if and .Values.ingress.enabled (eq .Values.ingress.type "ingressroute") }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "canon-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canon-proxy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressRoute.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressRoute.ingressClassName | quote }}
  {{- end }}
  entryPoints:
    {{- toYaml .Values.ingress.ingressRoute.tlsEntryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ required "ingress.host is required when ingress.enabled=true and ingress.type=ingressroute" .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "canon-proxy.fullname" . }}
          port: http
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "canon-proxy.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canon-proxy.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.ingressRoute.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressRoute.ingressClassName | quote }}
  {{- end }}
  entryPoints:
    {{- toYaml .Values.ingress.ingressRoute.httpEntryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      {{- with .Values.ingress.ingressRoute.httpMiddlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      services:
        - name: {{ include "canon-proxy.fullname" . }}
          port: http
{{- end }}
