apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "canon-proxy.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canon-proxy.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
