{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canon-proxy.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canon-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  smb-password: {{ .Values.secret.smbPassword | quote }}
  ftp-password: {{ .Values.secret.ftpPassword | quote }}
  s3-secret-key: {{ .Values.secret.s3SecretKey | quote }}
  azure-sas-token: {{ .Values.secret.azureSasToken | quote }}
  gcs-service-account-json: {{ .Values.secret.gcsServiceAccountJSON | quote }}
{{- end }}
