apiVersion: v1
kind: Service
metadata:
  name: {{ include "canon-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canon-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "canon-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
