apiVersion: v2
name: canon-proxy
description: >-
  Canon EOS PTP/IP proxy — discovers, downloads, and uploads camera images to a
  NAS or cloud storage
type: application
version: 1.2.2
appVersion: 1.2.2
